training:
  epoch_count: 20
  batch_size: 32
  learning_rate: 0.01

  validation_fraction: 0.6

  network:
    channel_count_hidden: 16
    convolution_kernel_size: 3
    mlp_hidden_unit_count: 64
    output_units: 3
    task_type: regression

evaluation:
  batch_size: 1024