training:
  epoch_count: 20
  batch_size: 64
  learning_rate: 5.e-3

  validation_fraction: 0.2

  network:
    channel_count_hidden: 15
    convolution_kernel_size: 5
    mlp_hidden_unit_count: 128
    output_units: 2
    task_type: classification_multiclass

evaluation:
  batch_size: 1024
  task_type: classification_multiclass