training:
  epoch_count: 60
  batch_size: 64
  learning_rate: 0.001

  validation_fraction: 0.75

  network:
    channel_count_hidden: 16
    convolution_kernel_size: 3
    mlp_hidden_unit_count: 64
    output_units: 3
    task_type: classification_multiclass

evaluation:
  batch_size: 1024