training:
  epoch_count: 100
  batch_size: 32
  learning_rate: 8.e-4

  validation_fraction: 0.2

  network:
    channel_count_hidden: 32
    convolution_kernel_size: 3
    mlp_hidden_unit_count: 64
    output_units: 8
    task_type: regression

evaluation:
  batch_size: 1024
  task_type: regression