training:
  epoch_count: 2
  batch_size: 32
  learning_rate: 8.e-4

  validation_fraction: 0.2

  network:
    channel_count_hidden: 16
    convolution_kernel_size: 3
    mlp_hidden_unit_count: 256
    output_units: 16
    task_type: regression

evaluation:
  batch_size: 1024
  task_type: regression