training:
  epoch_count: 50
  batch_size: 64
  learning_rate: 1.e-3

  validation_fraction: 0.8

  network:
    channel_count_hidden: 16
    convolution_kernel_size: 5
    mlp_hidden_unit_count: 64
    output_units: 3
    task_type: classification_multiclass

evaluation:
  batch_size: 1024