training:
  epoch_count: 1
  batch_size: 256
  learning_rate: 1.0e-3

  validation_fraction: 0.1

  network:
    channel_count_hidden: 4
    convolution_kernel_size: 3
    mlp_hidden_unit_count: 4
    output_units: 18
    task_type: regression

evaluation:
  batch_size: 1024
