training:
  epoch_count: 40
  batch_size: 32
  learning_rate: 1.e-4

  validation_fraction: 0.2

  network:
    channel_count_hidden: 16
    convolution_kernel_size: 5
    mlp_hidden_unit_count: 128
    output_units: 3
    task_type: classification_multiclass

evaluation:
  batch_size: 1024
  task_type: classification_multiclass